import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "../components/authprovider/AuthContext";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tele Medicine",
  description: "Generated by Shaiadul Basar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
